/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Countdown: typeof import('./../src/components/time/Countdown.vue')['default']
    DiscussingContiner: typeof import('./../src/components/room/DiscussingContiner.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HostPlayer: typeof import('./../src/components/player/HostPlayer.vue')['default']
    ImageDialog: typeof import('./../src/components/ImageDialog.vue')['default']
    LanguageButton: typeof import('./../src/components/LanguageButton.vue')['default']
    ManualDialog: typeof import('./../src/components/ManualDialog.vue')['default']
    ModalDialog: typeof import('./../src/components/ModalDialog.vue')['default']
    Player: typeof import('./../src/components/player/Player.vue')['default']
    PlayerContiner: typeof import('./../src/components/room/PlayerContiner.vue')['default']
    ProductContainer: typeof import('./../src/components/ProductContainer.vue')['default']
    ResultContiner: typeof import('./../src/components/room/ResultContiner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splat1: typeof import('./../src/components/splats/Splat1.vue')['default']
    Splat2: typeof import('./../src/components/splats/Splat2.vue')['default']
    Splat3: typeof import('./../src/components/splats/Splat3.vue')['default']
    Splat4: typeof import('./../src/components/splats/Splat4.vue')['default']
    Splat5: typeof import('./../src/components/splats/Splat5.vue')['default']
    Splat6: typeof import('./../src/components/splats/Splat6.vue')['default']
    SplatImage: typeof import('./../src/components/SplatImage.vue')['default']
    SquidTape: typeof import('./../src/components/SquidTape.vue')['default']
    Star: typeof import('./../src/components/splats/Star.vue')['default']
    TaskCard: typeof import('./../src/components/task/TaskCard.vue')['default']
    TaskCardHorizontal: typeof import('./../src/components/task/TaskCardHorizontal.vue')['default']
    TaskContiner: typeof import('./../src/components/task/TaskContiner.vue')['default']
    TaskDialog: typeof import('./../src/components/task/TaskDialog.vue')['default']
    TeamPlayer: typeof import('./../src/components/player/TeamPlayer.vue')['default']
    VoteContiner: typeof import('./../src/components/room/VoteContiner.vue')['default']
    VotePlayer: typeof import('./../src/components/player/VotePlayer.vue')['default']
    WaittingContiner: typeof import('./../src/components/room/WaittingContiner.vue')['default']
  }
}
